name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions: {}

jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Reject non-dev pull requests to main
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "Merge requests to main branch are only allowed from dev branch."
          exit 1
