name: Auto Tag, Release on PR Merge
on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

permissions:
  contents: write

jobs:
  tag-and-release:
    if: github.event.pull_request.merged == true && github.head_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 0
          ref: 'main' # Ensure we're tagging the main branch after the merge
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Determine Next Version Tag
        id: nextver
        run: |
          if [[ -f version.txt ]]; then
             NEXT_TAG=$(cat version.txt)
          else
            CURRENT_TAG=$(git tag --sort=-v:refname | head -n 1)
            if [[ $CURRENT_TAG == '' ]]; then 
               CURRENT_TAG='v0.1.0' # Start from v0.1.0 if no tags are found
            fi

            MAJOR=$(echo $CURRENT_TAG | cut -d '.' -f 1 | cut -c 2-)
            MINOR=$(echo $CURRENT_TAG | cut -d '.' -f 2)
            PATCH=$(echo $CURRENT_TAG | cut -d '.' -f 3)

            if [[ $PATCH -eq 9 ]]; then
              PATCH=0
              if [[ $MINOR -eq 9 ]]; then
                MINOR=0
                MAJOR=$((MAJOR+1))
              else
                MINOR=$((MINOR+1))
              fi
            else
              PATCH=$((PATCH+1))
            fi

            NEXT_TAG="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "Next version tag: $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_OUTPUT
          
      - name: Create and Push Tag
        run: |
          git tag ${{ steps.nextver.outputs.tag }}
          git push origin ${{ steps.nextver.outputs.tag }}
          
      - name: Create Release with Automated Release Notes
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.nextver.outputs.tag }}
          name: "Release ${{ steps.nextver.outputs.tag }}"
          prerelease: false
          generate_release_notes: true
